baseurl: "/"
title: "listaLists"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "Everything List"
  AuthorName: "GustavoEspindola"
  GitHubUser: "GustavoEspindola"
languageCode: "en-us"
metaDataFormat: "yaml"
buildFuture: true
defaultContentLanguage: "en"
enableEmoji: true
publishDir: docs