baseurl: "https://listalists.com/"
languageCode: "en-us"
title: "listaLists"
metaDataFormat: "yaml"
params:
  Subtitle: "Emprendimientos que hacen del mundo un lugar mejor"
  AuthorName: "Gustavo Espindola"