baseurl: "/"
title: "Trafkin"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "Trafkin"
  AuthorName: "GustavoEspindola"
  GitHubUser: "GustavoEspindola"
languageCode: "en-us"
defaultContentLanguage: "en"
enableEmoji: true
